; Generated by scriptc (LLVM backend) from /Users/tarwin/all/development/tinyjsapp/spike-scriptc/spike-backend.ts. Do not edit.

%ScrStr = type { i64, i64, i64 }
%ScrLogArg = type { i32, i64 }
%ScrVt = type { i64, i64, ptr }
%ScrUnion = type { i64, i32, ptr, ptr, ptr, i64 }
%ScrClosure = type { i64, ptr, i64, ptr }
%ScrFfiTable = type { ptr, i64, i64, ptr, i8, ptr, ptr, i64, i64, i64, ptr, ptr }
%ScrRegex = type { i64, ptr, ptr, ptr }
%ScrArr = type { i64, i64, i64, i32, ptr, ptr, ptr, ptr }
%ScrError = type { i64, ptr, ptr, ptr, ptr }
%ScrClassObj = type { i64, i64, i64, ptr, ptr }
%ScrEmitter = type { i64, ptr, ptr, ptr }
%ScrStream = type { i64, ptr, ptr, ptr, ptr }
%ScrCaught = type { i64, i32, double, i8, ptr, ptr, ptr, ptr }
%ScrBytes = type { i64, i64, i32, ptr, ptr }
%ScrBox = type { i64, i32, ptr, ptr, ptr, i64 }
%ScrJsonBuf = type { ptr, i64, i64, ptr, i64, i64 }
%ScrDynPath = type { ptr, ptr, i64 }
%ScrIslandModule = type { ptr, ptr, i64, i64, i32, ptr, i64, i64 }
%ScrIslandEdge = type { ptr, ptr, ptr, i32 }

@scr_error_vts = external global [5 x %ScrVt]
declare void @scr_init()
declare void @scr_lib_init(i32, ptr)
declare ptr @scr_str_retain_v(ptr)
declare void @scr_str_release_v(ptr)
declare ptr @scr_str_concat(ptr, ptr)
declare void @scr_str_release(ptr)
declare void @scr_console_log(i64, ptr)
declare void @scr_fs_append_file(ptr, ptr)
declare zeroext i1 @scr_exc_pending()
declare double @scr_str_utf16_len(ptr)
declare ptr @scr_str_cp_at(ptr, double)
declare zeroext i1 @scr_str_eq(ptr, ptr)
declare ptr @scr_process_argv()
declare double @scr_arr_len(ptr)
declare void @scr_arr_release(ptr)
declare void @scr_process_exit(double)
declare ptr @scr_arr_get_ref(ptr, double)
declare ptr @scr_union_new_ref(i32, ptr, ptr, ptr, ptr)
declare void @scr_union_release(ptr)
declare void @scr_fs_write_file(ptr, ptr)
declare ptr @scr_closure_new(ptr, i64)
declare void @scr_net_conn_thunk_sock(ptr, ptr)
declare ptr @scr_net_create_server(ptr, ptr)
declare ptr @scr_net_server_retain_v(ptr)
declare void @scr_net_server_release_v(ptr)
declare void @scr_net_listen_opts(ptr, double, ptr, i1 zeroext, ptr)
declare ptr @scr_arr_retain_v(ptr)
declare void @scr_arr_release_v(ptr)
declare double @llvm.floor.f64(double)
declare ptr @scr_box_get_ref(ptr)
declare void @scr_net_sock_write_str(ptr, ptr)
declare ptr @scr_net_sock_retain_v(ptr)
declare void @scr_net_sock_release_v(ptr)
declare zeroext i1 @scr_box_get_bool(ptr)
declare void @scr_box_set_bool(ptr, i1 zeroext)
declare void @scr_closure_release(ptr)
declare ptr @scr_bytes_retain_v(ptr)
declare void @scr_bytes_release_v(ptr)
declare ptr @scr_bytes_to_str(ptr, ptr)
declare void @scr_box_set_ref(ptr, ptr)
declare void @scr_bytes_release(ptr)
declare double @scr_str_index_of(ptr, ptr, double)
declare ptr @scr_str_slice(ptr, double, double)
declare void @scr_set_timeout(ptr, double)
declare ptr @scr_box_new_obj(ptr, ptr, ptr)
declare void @scr_box_release(ptr)
declare ptr @scr_box_new(i32)
declare void @scr_net_data_thunk_bytes(ptr, ptr)
declare void @scr_net_sock_on_data(ptr, ptr, ptr, i1 zeroext)
declare ptr @scr_union_retain_v(ptr)
declare void @scr_union_release_v(ptr)
declare double @scr_union_get_f64(ptr)
declare ptr @scr_f64_to_scrstr(double)
declare zeroext i1 @scr_child_kill(ptr, ptr)
declare void @scr_child_release_v(ptr)
declare ptr @scr_arr_new(i32, i64)
declare double @scr_arr_push_ref(ptr, ptr)
declare ptr @scr_spawn_opts(ptr, ptr, double, double, double, double, double, i1 zeroext, i1 zeroext, ptr, ptr)
declare ptr @scr_child_retain_v(ptr)
declare zeroext i1 @scr_child_has_pid(ptr)
declare double @scr_child_pid(ptr)
declare ptr @scr_union_new_f64(i32, double)
declare ptr @scr_str_new(ptr, i64)
declare i64 @strlen(ptr)
declare void @scr_child_on_exit(ptr, ptr, ptr)
declare ptr @scr_spawn(ptr, ptr)
declare void @scr_net_install()
declare void @scr_net_dyn_install()
declare zeroext i1 @scr_loop_run(ptr)
declare zeroext i1 @scr_report_unhandled_rejections()
declare void @scr_discard_unhandled_rejections()
declare void @scr_trap(ptr)

@sc_lit_0 = internal global { i64, i64, i64, [2 x i8] } { i64 -1, i64 1, i64 1, [2 x i8] c" \00" }
@sc_lit_1 = internal global { i64, i64, i64, [2 x i8] } { i64 -1, i64 1, i64 1, [2 x i8] c"\0A\00" }
@sc_lit_2 = internal global { i64, i64, i64, [1 x i8] } { i64 -1, i64 0, i64 0, [1 x i8] c"\00" }
@sc_lit_3 = internal global { i64, i64, i64, [2 x i8] } { i64 -1, i64 1, i64 1, [2 x i8] c"\5C\00" }
@sc_lit_4 = internal global { i64, i64, i64, [3 x i8] } { i64 -1, i64 2, i64 2, [3 x i8] c"\5C\5C\00" }
@sc_lit_5 = internal global { i64, i64, i64, [2 x i8] } { i64 -1, i64 1, i64 1, [2 x i8] c"\09\00" }
@sc_lit_6 = internal global { i64, i64, i64, [3 x i8] } { i64 -1, i64 2, i64 2, [3 x i8] c"\5Ct\00" }
@sc_lit_7 = internal global { i64, i64, i64, [2 x i8] } { i64 -1, i64 1, i64 1, [2 x i8] c"\0D\00" }
@sc_lit_8 = internal global { i64, i64, i64, [3 x i8] } { i64 -1, i64 2, i64 2, [3 x i8] c"\5Cr\00" }
@sc_lit_9 = internal global { i64, i64, i64, [3 x i8] } { i64 -1, i64 2, i64 2, [3 x i8] c"\5Cn\00" }
@sc_lit_10 = internal global { i64, i64, i64, [56 x i8] } { i64 -1, i64 55, i64 55, [56 x i8] c"usage: spike-backend <launcherPath> <pagePath> [--stay]\00" }
@sc_lit_11 = internal global { i64, i64, i64, [7 x i8] } { i64 -1, i64 6, i64 6, [7 x i8] c"--stay\00" }
@sc_lit_12 = internal global { i64, i64, i64, [24 x i8] } { i64 -1, i64 23, i64 23, [24 x i8] c"/tmp/scriptc-spike.sock\00" }
@sc_lit_13 = internal global { i64, i64, i64, [24 x i8] } { i64 -1, i64 23, i64 23, [24 x i8] c"/tmp/scriptc-spike.fifo\00" }
@sc_lit_14 = internal global { i64, i64, i64, [34 x i8] } { i64 -1, i64 33, i64 33, [34 x i8] c"/tmp/scriptc-spike-transcript.txt\00" }
@sc_lit_15 = internal global { i64, i64, i64, [10 x i8] } { i64 -1, i64 9, i64 9, [10 x i8] c"127.0.0.1\00" }
@sc_lit_16 = internal global { i64, i64, i64, [3 x i8] } { i64 -1, i64 2, i64 2, [3 x i8] c"->\00" }
@sc_lit_17 = internal global { i64, i64, i64, [28 x i8] } { i64 -1, i64 27, i64 27, [28 x i8] c"TITLE driven by scriptc \E2\9C\A8\00" }
@sc_lit_18 = internal global { i64, i64, i64, [49 x i8] } { i64 -1, i64 48, i64 48, [49 x i8] c"document.getElementById(\22status\22).textContent = \00" }
@sc_lit_19 = internal global { i64, i64, i64, [93 x i8] } { i64 -1, i64 92, i64 92, [93 x i8] c"\22backend says hello \E2\80\94 compiled TypeScript, \22 + (2 ** 10) + \22 bytes of runtime between us\22;\00" }
@sc_lit_20 = internal global { i64, i64, i64, [6 x i8] } { i64 -1, i64 5, i64 5, [6 x i8] c"EVAL \00" }
@sc_lit_21 = internal global { i64, i64, i64, [5 x i8] } { i64 -1, i64 4, i64 4, [5 x i8] c"utf8\00" }
@sc_lit_22 = internal global { i64, i64, i64, [3 x i8] } { i64 -1, i64 2, i64 2, [3 x i8] c"<-\00" }
@sc_lit_23 = internal global { i64, i64, i64, [5 x i8] } { i64 -1, i64 4, i64 4, [5 x i8] c"QUIT\00" }
@sc_lit_24 = internal global { i64, i64, i64, [3 x i8] } { i64 -1, i64 2, i64 2, [3 x i8] c"--\00" }
@sc_lit_25 = internal global { i64, i64, i64, [27 x i8] } { i64 -1, i64 26, i64 26, [27 x i8] c"relay attached to TCP side\00" }
@sc_lit_26 = internal global { i64, i64, i64, [22 x i8] } { i64 -1, i64 21, i64 21, [22 x i8] c"launcher exited code=\00" }
@sc_lit_27 = internal global { i64, i64, i64, [5 x i8] } { i64 -1, i64 4, i64 4, [5 x i8] c"null\00" }
@sc_lit_28 = internal global { i64, i64, i64, [8 x i8] } { i64 -1, i64 7, i64 7, [8 x i8] c"SIGTERM\00" }
@sc_lit_29 = internal global { i64, i64, i64, [14 x i8] } { i64 -1, i64 13, i64 13, [14 x i8] c"scriptc spike\00" }
@sc_lit_30 = internal global { i64, i64, i64, [8 x i8] } { i64 -1, i64 7, i64 7, [8 x i8] c"760x520\00" }
@sc_lit_31 = internal global { i64, i64, i64, [6 x i8] } { i64 -1, i64 5, i64 5, [6 x i8] c"0.0.0\00" }
@sc_lit_32 = internal global { i64, i64, i64, [14 x i8] } { i64 -1, i64 13, i64 13, [14 x i8] c"launcher pid \00" }
@sc_lit_33 = internal global { i64, i64, i64, [32 x i8] } { i64 -1, i64 31, i64 31, [32 x i8] c"backend listening on 127.0.0.1:\00" }
@sc_lit_34 = internal global { i64, i64, i64, [7 x i8] } { i64 -1, i64 6, i64 6, [7 x i8] c"rm -f \00" }
@sc_lit_35 = internal global { i64, i64, i64, [10 x i8] } { i64 -1, i64 9, i64 9, [10 x i8] c"; mkfifo \00" }
@sc_lit_36 = internal global { i64, i64, i64, [3 x i8] } { i64 -1, i64 2, i64 2, [3 x i8] c"; \00" }
@sc_lit_37 = internal global { i64, i64, i64, [8 x i8] } { i64 -1, i64 7, i64 7, [8 x i8] c"nc -lU \00" }
@sc_lit_38 = internal global { i64, i64, i64, [4 x i8] } { i64 -1, i64 3, i64 3, [4 x i8] c" < \00" }
@sc_lit_39 = internal global { i64, i64, i64, [17 x i8] } { i64 -1, i64 16, i64 16, [17 x i8] c" | nc 127.0.0.1 \00" }
@sc_lit_40 = internal global { i64, i64, i64, [4 x i8] } { i64 -1, i64 3, i64 3, [4 x i8] c" > \00" }
@sc_lit_41 = internal global { i64, i64, i64, [3 x i8] } { i64 -1, i64 2, i64 2, [3 x i8] c"sh\00" }
@sc_lit_42 = internal global { i64, i64, i64, [3 x i8] } { i64 -1, i64 2, i64 2, [3 x i8] c"-c\00" }
@sc_lit_43 = internal global { i64, i64, i64, [11 x i8] } { i64 -1, i64 10, i64 10, [11 x i8] c"relay pid \00" }

@sc_unit_0 = internal global %ScrUnion { i64 -1, i32 1, ptr null, ptr null, ptr null, i64 0 } ; u1 unit arm
@sc_unit_1 = internal global %ScrUnion { i64 -1, i32 1, ptr null, ptr null, ptr null, i64 0 } ; u4 unit arm
@sc_unit_2 = internal global %ScrUnion { i64 -1, i32 1, ptr null, ptr null, ptr null, i64 0 } ; u6 unit arm
@sc_unit_3 = internal global %ScrUnion { i64 -1, i32 0, ptr null, ptr null, ptr null, i64 0 } ; u7 unit arm

@sc_g_e_launcher = internal global ptr null ; launcher
@sc_g_e_page = internal global ptr null ; page
@sc_g_e_stay = internal global i1 false ; stay
@sc_g_e_PORT = internal global double 0x0000000000000000 ; PORT
@sc_g_e_SOCK = internal global ptr null ; SOCK
@sc_g_e_FIFO = internal global ptr null ; FIFO
@sc_g_e_LOG = internal global ptr null ; LOG
@sc_g_e_server = internal global ptr null ; server
@sc_g_e__x25_loaded = internal global i1 false ; %loaded

@sc_bad_tag_msg = internal constant [44 x i8] c"scriptc: internal error: invalid union tag\0A\00"
define internal void @sc_bad_tag() #0 {
entry:
  call void @scr_trap(ptr @sc_bad_tag_msg)
  unreachable
}

define internal ptr @sc_retain_box(ptr %b) #0 {
entry:
  %rc = load i64, ptr %b
  %imm = icmp eq i64 %rc, -1
  br i1 %imm, label %done, label %inc
inc:
  %n = add i64 %rc, 1
  store i64 %n, ptr %b
  %colorp = getelementptr i8, ptr %b, i64 -16
  store i32 0, ptr %colorp ; mark live
  br label %done
done:
  ret ptr %b
}

define internal void @sc_cx_0(ptr %cb, i1 zeroext %has, double %code, ptr %sig) #0 { ; child exit (code, signal)
entry:
  %uslot = alloca ptr
  %sslot = alloca ptr
  br i1 %has, label %num, label %nonum
num:
  %u1 = call ptr @scr_union_new_f64(i32 0, double %code)
  store ptr %u1, ptr %uslot
  br label %sigq
nonum:
  store ptr @sc_unit_2, ptr %uslot
  br label %sigq
sigq:
  %hassig = icmp ne ptr %sig, null
  br i1 %hassig, label %sigs, label %signull
sigs:
  %len = call i64 @strlen(ptr %sig)
  %ss = call ptr @scr_str_new(ptr %sig, i64 %len)
  %su = call ptr @scr_union_new_ref(i32 1, ptr %ss, ptr @scr_str_retain_v, ptr @scr_str_release_v, ptr null)
  store ptr %su, ptr %sslot
  br label %go
signull:
  store ptr @sc_unit_3, ptr %sslot
  br label %go
go:
  %u = load ptr, ptr %uslot
  %s = load ptr, ptr %sslot
  %fnp = getelementptr inbounds %ScrClosure, ptr %cb, i64 0, i32 1
  %fn = load ptr, ptr %fnp
  call void %fn(ptr %cb, ptr %u, ptr %s)
  ret void
}

define internal void @sc_f_record(ptr %p_sc_l_dir_0, ptr %p_sc_l_line_0) #0 { ; record
entry:
  %sc_l_dir_0 = alloca ptr ; dir
  %sc_l_line_0 = alloca ptr ; line
  %sc_l_entry_0 = alloca ptr ; entry
  %logargs = alloca [1 x %ScrLogArg]
  store ptr null, ptr %sc_l_entry_0
  store ptr %p_sc_l_dir_0, ptr %sc_l_dir_0
  store ptr %p_sc_l_line_0, ptr %sc_l_line_0
  %t0 = load ptr, ptr %sc_l_dir_0
  %t1 = call ptr @scr_str_retain_v(ptr %t0)
  %t2 = call ptr @scr_str_retain_v(ptr @sc_lit_0)
  %t3 = call ptr @scr_str_concat(ptr %t1, ptr %t2)
  %t4 = load ptr, ptr %sc_l_line_0
  %t5 = call ptr @scr_str_retain_v(ptr %t4)
  %t6 = call ptr @scr_str_concat(ptr %t3, ptr %t5)
  store ptr %t6, ptr %sc_l_entry_0
  call void @scr_str_release(ptr %t1)
  call void @scr_str_release(ptr %t2)
  call void @scr_str_release(ptr %t3)
  call void @scr_str_release(ptr %t5)
  %t7 = load ptr, ptr %sc_l_entry_0
  %t8 = call ptr @scr_str_retain_v(ptr %t7)
  %t9 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 0
  store i32 1, ptr %t9
  %t10 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 1
  store ptr %t8, ptr %t10
  call void @scr_console_log(i64 1, ptr %logargs)
  call void @scr_str_release(ptr %t8)
  %t11 = load ptr, ptr @sc_g_e_LOG
  %t12 = call ptr @scr_str_retain_v(ptr %t11)
  %t13 = load ptr, ptr %sc_l_entry_0
  %t14 = call ptr @scr_str_retain_v(ptr %t13)
  %t15 = call ptr @scr_str_retain_v(ptr @sc_lit_1)
  %t16 = call ptr @scr_str_concat(ptr %t14, ptr %t15)
  call void @scr_fs_append_file(ptr %t12, ptr %t16)
  %t17 = call zeroext i1 @scr_exc_pending()
  br i1 %t17, label %exc.u0, label %exc.k1
exc.u0:
  call void @scr_str_release(ptr %t12)
  call void @scr_str_release(ptr %t14)
  call void @scr_str_release(ptr %t15)
  call void @scr_str_release(ptr %t16)
  %t18 = load ptr, ptr %sc_l_dir_0
  call void @scr_str_release(ptr %t18)
  %t19 = load ptr, ptr %sc_l_line_0
  call void @scr_str_release(ptr %t19)
  %t20 = load ptr, ptr %sc_l_entry_0
  call void @scr_str_release(ptr %t20)
  ret void
exc.k1:
  call void @scr_str_release(ptr %t12)
  call void @scr_str_release(ptr %t14)
  call void @scr_str_release(ptr %t15)
  call void @scr_str_release(ptr %t16)
  %t21 = load ptr, ptr %sc_l_dir_0
  call void @scr_str_release(ptr %t21)
  %t22 = load ptr, ptr %sc_l_line_0
  call void @scr_str_release(ptr %t22)
  %t23 = load ptr, ptr %sc_l_entry_0
  call void @scr_str_release(ptr %t23)
  ret void
}

define internal ptr @sc_f_esc(ptr %p_sc_l_s_0) #0 { ; esc
entry:
  %sc_l_s_0 = alloca ptr ; s
  %sc_l_out_0 = alloca ptr ; out
  %sc_l__x25_strof_0 = alloca ptr ; %strof
  %sc_l__x25_iterof_0 = alloca double ; %iterof
  %sc_l_ch_0 = alloca ptr ; ch
  store ptr null, ptr %sc_l_out_0
  store ptr null, ptr %sc_l__x25_strof_0
  store ptr null, ptr %sc_l_ch_0
  store ptr %p_sc_l_s_0, ptr %sc_l_s_0
  %t0 = call ptr @scr_str_retain_v(ptr @sc_lit_2)
  store ptr %t0, ptr %sc_l_out_0
  %t1 = load ptr, ptr %sc_l_s_0
  %t2 = call ptr @scr_str_retain_v(ptr %t1)
  store ptr %t2, ptr %sc_l__x25_strof_0
  store double 0x0000000000000000, ptr %sc_l__x25_iterof_0
  br label %loop.c0
loop.c0:
  %t3 = load double, ptr %sc_l__x25_iterof_0
  %t4 = load ptr, ptr %sc_l__x25_strof_0
  %t5 = call ptr @scr_str_retain_v(ptr %t4)
  %t6 = call double @scr_str_utf16_len(ptr %t5)
  %t7 = fcmp olt double %t3, %t6
  call void @scr_str_release(ptr %t5)
  br i1 %t7, label %loop.b1, label %loop.e2
loop.b1:
  %t8 = load ptr, ptr %sc_l__x25_strof_0
  %t9 = call ptr @scr_str_retain_v(ptr %t8)
  %t10 = load double, ptr %sc_l__x25_iterof_0
  %t11 = call ptr @scr_str_cp_at(ptr %t9, double %t10)
  store ptr %t11, ptr %sc_l_ch_0
  call void @scr_str_release(ptr %t9)
  %t12 = load double, ptr %sc_l__x25_iterof_0
  %t13 = load ptr, ptr %sc_l_ch_0
  %t14 = call ptr @scr_str_retain_v(ptr %t13)
  %t15 = call double @scr_str_utf16_len(ptr %t14)
  %t16 = fadd double %t12, %t15
  store double %t16, ptr %sc_l__x25_iterof_0
  call void @scr_str_release(ptr %t14)
  %t17 = load ptr, ptr %sc_l_ch_0
  %t18 = call ptr @scr_str_retain_v(ptr %t17)
  %t19 = call ptr @scr_str_retain_v(ptr @sc_lit_3)
  %t20 = call zeroext i1 @scr_str_eq(ptr %t18, ptr %t19)
  call void @scr_str_release(ptr %t18)
  call void @scr_str_release(ptr %t19)
  br i1 %t20, label %if.t3, label %if.f5
if.t3:
  %t21 = load ptr, ptr %sc_l_out_0
  %t22 = call ptr @scr_str_retain_v(ptr %t21)
  %t23 = call ptr @scr_str_retain_v(ptr @sc_lit_4)
  %t24 = call ptr @scr_str_concat(ptr %t22, ptr %t23)
  %t25 = load ptr, ptr %sc_l_out_0
  call void @scr_str_release(ptr %t25)
  store ptr %t24, ptr %sc_l_out_0
  call void @scr_str_release(ptr %t22)
  call void @scr_str_release(ptr %t23)
  br label %if.j4
if.f5:
  %t26 = load ptr, ptr %sc_l_ch_0
  %t27 = call ptr @scr_str_retain_v(ptr %t26)
  %t28 = call ptr @scr_str_retain_v(ptr @sc_lit_5)
  %t29 = call zeroext i1 @scr_str_eq(ptr %t27, ptr %t28)
  call void @scr_str_release(ptr %t27)
  call void @scr_str_release(ptr %t28)
  br i1 %t29, label %if.t6, label %if.f8
if.t6:
  %t30 = load ptr, ptr %sc_l_out_0
  %t31 = call ptr @scr_str_retain_v(ptr %t30)
  %t32 = call ptr @scr_str_retain_v(ptr @sc_lit_6)
  %t33 = call ptr @scr_str_concat(ptr %t31, ptr %t32)
  %t34 = load ptr, ptr %sc_l_out_0
  call void @scr_str_release(ptr %t34)
  store ptr %t33, ptr %sc_l_out_0
  call void @scr_str_release(ptr %t31)
  call void @scr_str_release(ptr %t32)
  br label %if.j7
if.f8:
  %t35 = load ptr, ptr %sc_l_ch_0
  %t36 = call ptr @scr_str_retain_v(ptr %t35)
  %t37 = call ptr @scr_str_retain_v(ptr @sc_lit_7)
  %t38 = call zeroext i1 @scr_str_eq(ptr %t36, ptr %t37)
  call void @scr_str_release(ptr %t36)
  call void @scr_str_release(ptr %t37)
  br i1 %t38, label %if.t9, label %if.f11
if.t9:
  %t39 = load ptr, ptr %sc_l_out_0
  %t40 = call ptr @scr_str_retain_v(ptr %t39)
  %t41 = call ptr @scr_str_retain_v(ptr @sc_lit_8)
  %t42 = call ptr @scr_str_concat(ptr %t40, ptr %t41)
  %t43 = load ptr, ptr %sc_l_out_0
  call void @scr_str_release(ptr %t43)
  store ptr %t42, ptr %sc_l_out_0
  call void @scr_str_release(ptr %t40)
  call void @scr_str_release(ptr %t41)
  br label %if.j10
if.f11:
  %t44 = load ptr, ptr %sc_l_ch_0
  %t45 = call ptr @scr_str_retain_v(ptr %t44)
  %t46 = call ptr @scr_str_retain_v(ptr @sc_lit_1)
  %t47 = call zeroext i1 @scr_str_eq(ptr %t45, ptr %t46)
  call void @scr_str_release(ptr %t45)
  call void @scr_str_release(ptr %t46)
  br i1 %t47, label %if.t12, label %if.f14
if.t12:
  %t48 = load ptr, ptr %sc_l_out_0
  %t49 = call ptr @scr_str_retain_v(ptr %t48)
  %t50 = call ptr @scr_str_retain_v(ptr @sc_lit_9)
  %t51 = call ptr @scr_str_concat(ptr %t49, ptr %t50)
  %t52 = load ptr, ptr %sc_l_out_0
  call void @scr_str_release(ptr %t52)
  store ptr %t51, ptr %sc_l_out_0
  call void @scr_str_release(ptr %t49)
  call void @scr_str_release(ptr %t50)
  br label %if.j13
if.f14:
  %t53 = load ptr, ptr %sc_l_out_0
  %t54 = call ptr @scr_str_retain_v(ptr %t53)
  %t55 = load ptr, ptr %sc_l_ch_0
  %t56 = call ptr @scr_str_retain_v(ptr %t55)
  %t57 = call ptr @scr_str_concat(ptr %t54, ptr %t56)
  %t58 = load ptr, ptr %sc_l_out_0
  call void @scr_str_release(ptr %t58)
  store ptr %t57, ptr %sc_l_out_0
  call void @scr_str_release(ptr %t54)
  call void @scr_str_release(ptr %t56)
  br label %if.j13
if.j13:
  br label %if.j10
if.j10:
  br label %if.j7
if.j7:
  br label %if.j4
if.j4:
  %t59 = load ptr, ptr %sc_l_ch_0
  call void @scr_str_release(ptr %t59)
  br label %loop.c0
loop.e2:
  %t60 = load ptr, ptr %sc_l__x25_strof_0
  call void @scr_str_release(ptr %t60)
  %t61 = load ptr, ptr %sc_l_out_0
  %t62 = call ptr @scr_str_retain_v(ptr %t61)
  %t63 = load ptr, ptr %sc_l_s_0
  call void @scr_str_release(ptr %t63)
  %t64 = load ptr, ptr %sc_l_out_0
  call void @scr_str_release(ptr %t64)
  ret ptr %t62
}

define internal void @sc_f__x25_init_0() #0 { ; %init.0
entry:
  %s16 = alloca i1
  %s21 = alloca i1
  %logargs = alloca [1 x %ScrLogArg]
  %t0 = load i1, ptr @sc_g_e__x25_loaded
  br i1 %t0, label %if.t0, label %if.j1
if.t0:
  ret void
if.j1:
  store i1 true, ptr @sc_g_e__x25_loaded
  %t1 = call ptr @scr_process_argv()
  %t2 = call double @scr_arr_len(ptr %t1)
  %t3 = fcmp olt double %t2, 0x4010000000000000
  call void @scr_arr_release(ptr %t1)
  br i1 %t3, label %if.t2, label %if.j3
if.t2:
  %t4 = call ptr @scr_str_retain_v(ptr @sc_lit_10)
  %t5 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 0
  store i32 1, ptr %t5
  %t6 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 1
  store ptr %t4, ptr %t6
  call void @scr_console_log(i64 1, ptr %logargs)
  call void @scr_str_release(ptr %t4)
  call void @scr_process_exit(double 0x3FF0000000000000)
  br label %if.j3
if.j3:
  %t7 = call ptr @scr_process_argv()
  %t8 = call ptr @scr_arr_get_ref(ptr %t7, double 0x4000000000000000)
  %t9 = load ptr, ptr @sc_g_e_launcher
  call void @scr_str_release(ptr %t9)
  store ptr %t8, ptr @sc_g_e_launcher
  call void @scr_arr_release(ptr %t7)
  %t10 = call ptr @scr_process_argv()
  %t11 = call ptr @scr_arr_get_ref(ptr %t10, double 0x4008000000000000)
  %t12 = load ptr, ptr @sc_g_e_page
  call void @scr_str_release(ptr %t12)
  store ptr %t11, ptr @sc_g_e_page
  call void @scr_arr_release(ptr %t10)
  %t13 = call ptr @scr_process_argv()
  %t14 = call double @scr_arr_len(ptr %t13)
  %t15 = fcmp ogt double %t14, 0x4010000000000000
  store i1 %t15, ptr %s16
  br i1 %t15, label %log.r4, label %log.j5
log.r4:
  %t17 = call ptr @scr_process_argv()
  %t18 = call ptr @sc_f__x25_arr_idxOr_0(ptr %t17, double 0x4010000000000000)
  %t19 = call ptr @scr_str_retain_v(ptr @sc_lit_11)
  %t20 = call ptr @scr_union_new_ref(i32 0, ptr %t19, ptr @scr_str_retain_v, ptr @scr_str_release_v, ptr null)
  %t22 = getelementptr inbounds %ScrUnion, ptr %t18, i64 0, i32 1
  %t23 = load i32, ptr %t22
  %t24 = getelementptr inbounds %ScrUnion, ptr %t20, i64 0, i32 1
  %t25 = load i32, ptr %t24
  %t26 = icmp eq i32 %t23, %t25
  store i1 false, ptr %s21
  br i1 %t26, label %ue.s7, label %ue.j6
ue.s7:
  %t27 = getelementptr inbounds %ScrUnion, ptr %t18, i64 0, i32 1
  %t28 = load i32, ptr %t27
  switch i32 %t28, label %u.bad8 [ i32 0, label %u.a9 i32 1, label %u.a10 ]
u.a9:
  %t29 = getelementptr inbounds %ScrUnion, ptr %t18, i64 0, i32 5
  %t30 = load ptr, ptr %t29
  %t31 = getelementptr inbounds %ScrUnion, ptr %t20, i64 0, i32 5
  %t32 = load ptr, ptr %t31
  %t33 = call zeroext i1 @scr_str_eq(ptr %t30, ptr %t32)
  store i1 %t33, ptr %s21
  br label %ue.j6
u.a10:
  store i1 true, ptr %s21
  br label %ue.j6
u.bad8:
  call void @sc_bad_tag()
  unreachable
ue.j6:
  %t34 = load i1, ptr %s21
  store i1 %t34, ptr %s16
  call void @scr_union_release(ptr %t18)
  call void @scr_union_release(ptr %t20)
  br label %log.j5
log.j5:
  %t35 = load i1, ptr %s16
  store i1 %t35, ptr @sc_g_e_stay
  call void @scr_arr_release(ptr %t13)
  store double 0x40C1608000000000, ptr @sc_g_e_PORT
  %t36 = call ptr @scr_str_retain_v(ptr @sc_lit_12)
  %t37 = load ptr, ptr @sc_g_e_SOCK
  call void @scr_str_release(ptr %t37)
  store ptr %t36, ptr @sc_g_e_SOCK
  %t38 = call ptr @scr_str_retain_v(ptr @sc_lit_13)
  %t39 = load ptr, ptr @sc_g_e_FIFO
  call void @scr_str_release(ptr %t39)
  store ptr %t38, ptr @sc_g_e_FIFO
  %t40 = call ptr @scr_str_retain_v(ptr @sc_lit_14)
  %t41 = load ptr, ptr @sc_g_e_LOG
  call void @scr_str_release(ptr %t41)
  store ptr %t40, ptr @sc_g_e_LOG
  %t42 = load ptr, ptr @sc_g_e_LOG
  %t43 = call ptr @scr_str_retain_v(ptr %t42)
  %t44 = call ptr @scr_str_retain_v(ptr @sc_lit_2)
  call void @scr_fs_write_file(ptr %t43, ptr %t44)
  %t45 = call zeroext i1 @scr_exc_pending()
  br i1 %t45, label %exc.u11, label %exc.k12
exc.u11:
  call void @scr_str_release(ptr %t43)
  call void @scr_str_release(ptr %t44)
  ret void
exc.k12:
  call void @scr_str_release(ptr %t43)
  call void @scr_str_release(ptr %t44)
  %t46 = call ptr @scr_closure_new(ptr @sc_f__x25_fn0, i64 0)
  %t47 = call ptr @scr_net_create_server(ptr %t46, ptr @scr_net_conn_thunk_sock)
  %t48 = load ptr, ptr @sc_g_e_server
  call void @scr_net_server_release_v(ptr %t48)
  store ptr %t47, ptr @sc_g_e_server
  %t49 = load ptr, ptr @sc_g_e_server
  %t50 = call ptr @scr_net_server_retain_v(ptr %t49)
  %t51 = load double, ptr @sc_g_e_PORT
  %t52 = call ptr @scr_str_retain_v(ptr @sc_lit_15)
  %t53 = call ptr @scr_closure_new(ptr @sc_f__x25_fn7, i64 0)
  call void @scr_net_listen_opts(ptr %t50, double %t51, ptr %t52, i1 false, ptr %t53)
  call void @scr_net_server_release_v(ptr %t50)
  call void @scr_str_release(ptr %t52)
  ret void
}

define internal void @sc_f__x25_main() #0 { ; %main
entry:
  call void @sc_f__x25_init_0()
  %t0 = call zeroext i1 @scr_exc_pending()
  br i1 %t0, label %exc.u0, label %exc.k1
exc.u0:
  ret void
exc.k1:
  ret void
}

define internal ptr @sc_f__x25_arr_idxOr_0(ptr %p_sc_l_a_0, double %p_sc_l_i_0) #0 { ; %arr.idxOr.0
entry:
  %sc_l_a_0 = alloca ptr ; a
  %sc_l_i_0 = alloca double ; i
  %sc_l_n_0 = alloca double ; n
  %sc_l_v_0 = alloca ptr ; v
  store ptr null, ptr %sc_l_v_0
  store ptr %p_sc_l_a_0, ptr %sc_l_a_0
  store double %p_sc_l_i_0, ptr %sc_l_i_0
  %t0 = load ptr, ptr %sc_l_a_0
  %t1 = call ptr @scr_arr_retain_v(ptr %t0)
  %t2 = call double @scr_arr_len(ptr %t1)
  store double %t2, ptr %sc_l_n_0
  call void @scr_arr_release(ptr %t1)
  %t3 = load double, ptr %sc_l_i_0
  %t4 = load double, ptr %sc_l_i_0
  %t5 = fcmp une double %t3, %t4
  br i1 %t5, label %if.t0, label %if.j1
if.t0:
  %t6 = load ptr, ptr %sc_l_a_0
  call void @scr_arr_release(ptr %t6)
  ret ptr @sc_unit_0
if.j1:
  %t7 = load double, ptr %sc_l_i_0
  %t8 = fcmp olt double %t7, 0x0000000000000000
  br i1 %t8, label %if.t2, label %if.j3
if.t2:
  %t9 = load ptr, ptr %sc_l_a_0
  call void @scr_arr_release(ptr %t9)
  ret ptr @sc_unit_0
if.j3:
  %t10 = load double, ptr %sc_l_i_0
  %t11 = load double, ptr %sc_l_n_0
  %t12 = fcmp oge double %t10, %t11
  br i1 %t12, label %if.t4, label %if.j5
if.t4:
  %t13 = load ptr, ptr %sc_l_a_0
  call void @scr_arr_release(ptr %t13)
  ret ptr @sc_unit_0
if.j5:
  %t14 = load double, ptr %sc_l_i_0
  %t15 = call double @llvm.floor.f64(double %t14)
  %t16 = load double, ptr %sc_l_i_0
  %t17 = fcmp olt double %t15, %t16
  br i1 %t17, label %if.t6, label %if.j7
if.t6:
  %t18 = load ptr, ptr %sc_l_a_0
  call void @scr_arr_release(ptr %t18)
  ret ptr @sc_unit_0
if.j7:
  %t19 = load ptr, ptr %sc_l_a_0
  %t20 = call ptr @scr_arr_retain_v(ptr %t19)
  %t21 = load double, ptr %sc_l_i_0
  %t22 = call ptr @scr_arr_get_ref(ptr %t20, double %t21)
  store ptr %t22, ptr %sc_l_v_0
  call void @scr_arr_release(ptr %t20)
  %t23 = load ptr, ptr %sc_l_v_0
  %t24 = call ptr @scr_str_retain_v(ptr %t23)
  %t25 = call ptr @scr_union_new_ref(i32 0, ptr %t24, ptr @scr_str_retain_v, ptr @scr_str_release_v, ptr null)
  %t26 = load ptr, ptr %sc_l_a_0
  call void @scr_arr_release(ptr %t26)
  %t27 = load ptr, ptr %sc_l_v_0
  call void @scr_str_release(ptr %t27)
  ret ptr %t25
}

define internal void @sc_f__x25_fn1_send(ptr %sc_env, ptr %p_sc_l_line_0) #0 { ; %fn1_send
entry:
  %sc_l_line_0 = alloca ptr ; line
  %sc_l_conn_0 = alloca ptr ; conn
  %t0 = getelementptr inbounds %ScrClosure, ptr %sc_env, i64 1 ; caps
  %t1 = getelementptr inbounds ptr, ptr %t0, i64 0 ; caps[0]
  %t2 = load ptr, ptr %t1
  store ptr %t2, ptr %sc_l_conn_0 ; captured conn
  store ptr %p_sc_l_line_0, ptr %sc_l_line_0
  %t3 = call ptr @scr_str_retain_v(ptr @sc_lit_16)
  %t4 = load ptr, ptr %sc_l_line_0
  %t5 = call ptr @scr_str_retain_v(ptr %t4)
  call void @sc_f_record(ptr %t3, ptr %t5)
  %t6 = call zeroext i1 @scr_exc_pending()
  br i1 %t6, label %exc.u0, label %exc.k1
exc.u0:
  %t7 = load ptr, ptr %sc_l_line_0
  call void @scr_str_release(ptr %t7)
  ret void
exc.k1:
  %t8 = load ptr, ptr %sc_l_conn_0
  %t9 = call ptr @scr_box_get_ref(ptr %t8)
  %t10 = load ptr, ptr %sc_l_line_0
  %t11 = call ptr @scr_str_retain_v(ptr %t10)
  %t12 = call ptr @scr_str_retain_v(ptr @sc_lit_1)
  %t13 = call ptr @scr_str_concat(ptr %t11, ptr %t12)
  call void @scr_net_sock_write_str(ptr %t9, ptr %t13)
  call void @scr_net_sock_release_v(ptr %t9)
  call void @scr_str_release(ptr %t11)
  call void @scr_str_release(ptr %t12)
  call void @scr_str_release(ptr %t13)
  %t14 = load ptr, ptr %sc_l_line_0
  call void @scr_str_release(ptr %t14)
  ret void
}

define internal void @sc_f__x25_fn2_greet(ptr %sc_env) #0 { ; %fn2_greet
entry:
  %sc_l_greeted_0 = alloca ptr ; greeted
  %sc_l_send_0 = alloca ptr ; send
  %sc_l_js_0 = alloca ptr ; js
  store ptr null, ptr %sc_l_js_0
  %t0 = getelementptr inbounds %ScrClosure, ptr %sc_env, i64 1 ; caps
  %t1 = getelementptr inbounds ptr, ptr %t0, i64 0 ; caps[0]
  %t2 = load ptr, ptr %t1
  store ptr %t2, ptr %sc_l_greeted_0 ; captured greeted
  %t3 = getelementptr inbounds %ScrClosure, ptr %sc_env, i64 1 ; caps
  %t4 = getelementptr inbounds ptr, ptr %t3, i64 1 ; caps[1]
  %t5 = load ptr, ptr %t4
  store ptr %t5, ptr %sc_l_send_0 ; captured send
  %t6 = load ptr, ptr %sc_l_greeted_0
  %t7 = call zeroext i1 @scr_box_get_bool(ptr %t6)
  br i1 %t7, label %if.t0, label %if.j1
if.t0:
  ret void
if.j1:
  %t8 = load ptr, ptr %sc_l_greeted_0
  call void @scr_box_set_bool(ptr %t8, i1 true)
  %t9 = load ptr, ptr %sc_l_send_0
  %t10 = call ptr @scr_box_get_ref(ptr %t9)
  %t11 = call ptr @scr_str_retain_v(ptr @sc_lit_17)
  %t12 = getelementptr inbounds %ScrClosure, ptr %t10, i64 0, i32 1
  %t13 = load ptr, ptr %t12
  call void %t13(ptr %t10, ptr %t11)
  %t14 = call zeroext i1 @scr_exc_pending()
  br i1 %t14, label %exc.u2, label %exc.k3
exc.u2:
  call void @scr_closure_release(ptr %t10)
  ret void
exc.k3:
  call void @scr_closure_release(ptr %t10)
  %t15 = call ptr @scr_str_retain_v(ptr @sc_lit_18)
  %t16 = call ptr @scr_str_retain_v(ptr @sc_lit_19)
  %t17 = call ptr @scr_str_concat(ptr %t15, ptr %t16)
  store ptr %t17, ptr %sc_l_js_0
  call void @scr_str_release(ptr %t15)
  call void @scr_str_release(ptr %t16)
  %t18 = load ptr, ptr %sc_l_send_0
  %t19 = call ptr @scr_box_get_ref(ptr %t18)
  %t20 = call ptr @scr_str_retain_v(ptr @sc_lit_20)
  %t21 = load ptr, ptr %sc_l_js_0
  %t22 = call ptr @scr_str_retain_v(ptr %t21)
  %t23 = call ptr @sc_f_esc(ptr %t22)
  %t24 = call ptr @scr_str_concat(ptr %t20, ptr %t23)
  %t25 = getelementptr inbounds %ScrClosure, ptr %t19, i64 0, i32 1
  %t26 = load ptr, ptr %t25
  call void %t26(ptr %t19, ptr %t24)
  %t27 = call zeroext i1 @scr_exc_pending()
  br i1 %t27, label %exc.u4, label %exc.k5
exc.u4:
  call void @scr_closure_release(ptr %t19)
  call void @scr_str_release(ptr %t20)
  call void @scr_str_release(ptr %t23)
  %t28 = load ptr, ptr %sc_l_js_0
  call void @scr_str_release(ptr %t28)
  ret void
exc.k5:
  call void @scr_closure_release(ptr %t19)
  call void @scr_str_release(ptr %t20)
  call void @scr_str_release(ptr %t23)
  %t29 = load ptr, ptr %sc_l_js_0
  call void @scr_str_release(ptr %t29)
  ret void
}

define internal void @sc_f__x25_fn3(ptr %sc_env, ptr %p_sc_l_chunk_0) #0 { ; %fn3
entry:
  %sc_l_chunk_0 = alloca ptr ; chunk
  %sc_l_buf_0 = alloca ptr ; buf
  %sc_l_i_0 = alloca double ; i
  %sc_l_line_0 = alloca ptr ; line
  %sc_l_sawLauncher_0 = alloca ptr ; sawLauncher
  %sc_l_greet_0 = alloca ptr ; greet
  store ptr null, ptr %sc_l_line_0
  %t0 = getelementptr inbounds %ScrClosure, ptr %sc_env, i64 1 ; caps
  %t1 = getelementptr inbounds ptr, ptr %t0, i64 0 ; caps[0]
  %t2 = load ptr, ptr %t1
  store ptr %t2, ptr %sc_l_buf_0 ; captured buf
  %t3 = getelementptr inbounds %ScrClosure, ptr %sc_env, i64 1 ; caps
  %t4 = getelementptr inbounds ptr, ptr %t3, i64 1 ; caps[1]
  %t5 = load ptr, ptr %t4
  store ptr %t5, ptr %sc_l_sawLauncher_0 ; captured sawLauncher
  %t6 = getelementptr inbounds %ScrClosure, ptr %sc_env, i64 1 ; caps
  %t7 = getelementptr inbounds ptr, ptr %t6, i64 2 ; caps[2]
  %t8 = load ptr, ptr %t7
  store ptr %t8, ptr %sc_l_greet_0 ; captured greet
  store ptr %p_sc_l_chunk_0, ptr %sc_l_chunk_0
  %t9 = load ptr, ptr %sc_l_buf_0
  %t10 = call ptr @scr_box_get_ref(ptr %t9)
  %t11 = load ptr, ptr %sc_l_chunk_0
  %t12 = call ptr @scr_bytes_retain_v(ptr %t11)
  %t13 = call ptr @scr_str_retain_v(ptr @sc_lit_21)
  %t14 = call ptr @scr_bytes_to_str(ptr %t12, ptr %t13)
  %t15 = call ptr @scr_str_concat(ptr %t10, ptr %t14)
  %t16 = load ptr, ptr %sc_l_buf_0
  call void @scr_box_set_ref(ptr %t16, ptr %t15)
  call void @scr_str_release(ptr %t10)
  call void @scr_bytes_release(ptr %t12)
  call void @scr_str_release(ptr %t13)
  call void @scr_str_release(ptr %t14)
  %t17 = load ptr, ptr %sc_l_buf_0
  %t18 = call ptr @scr_box_get_ref(ptr %t17)
  %t19 = call ptr @scr_str_retain_v(ptr @sc_lit_1)
  %t20 = call double @scr_str_index_of(ptr %t18, ptr %t19, double 0x0000000000000000)
  store double %t20, ptr %sc_l_i_0
  call void @scr_str_release(ptr %t18)
  call void @scr_str_release(ptr %t19)
  br label %loop.c0
loop.c0:
  %t21 = load double, ptr %sc_l_i_0
  %t22 = fcmp oge double %t21, 0x0000000000000000
  br i1 %t22, label %loop.b1, label %loop.e2
loop.b1:
  %t23 = load ptr, ptr %sc_l_buf_0
  %t24 = call ptr @scr_box_get_ref(ptr %t23)
  %t25 = load double, ptr %sc_l_i_0
  %t26 = call ptr @scr_str_slice(ptr %t24, double 0x0000000000000000, double %t25)
  store ptr %t26, ptr %sc_l_line_0
  call void @scr_str_release(ptr %t24)
  %t27 = load ptr, ptr %sc_l_buf_0
  %t28 = call ptr @scr_box_get_ref(ptr %t27)
  %t29 = load double, ptr %sc_l_i_0
  %t30 = fadd double %t29, 0x3FF0000000000000
  %t31 = call ptr @scr_str_slice(ptr %t28, double %t30, double 0x7FF0000000000000)
  %t32 = load ptr, ptr %sc_l_buf_0
  call void @scr_box_set_ref(ptr %t32, ptr %t31)
  call void @scr_str_release(ptr %t28)
  %t33 = call ptr @scr_str_retain_v(ptr @sc_lit_22)
  %t34 = load ptr, ptr %sc_l_line_0
  %t35 = call ptr @scr_str_retain_v(ptr %t34)
  call void @sc_f_record(ptr %t33, ptr %t35)
  %t36 = call zeroext i1 @scr_exc_pending()
  br i1 %t36, label %exc.u3, label %exc.k4
exc.u3:
  %t37 = load ptr, ptr %sc_l_line_0
  call void @scr_str_release(ptr %t37)
  %t38 = load ptr, ptr %sc_l_chunk_0
  call void @scr_bytes_release(ptr %t38)
  ret void
exc.k4:
  %t39 = load ptr, ptr %sc_l_sawLauncher_0
  %t40 = call zeroext i1 @scr_box_get_bool(ptr %t39)
  %t41 = xor i1 %t40, true
  br i1 %t41, label %if.t5, label %if.j6
if.t5:
  %t42 = load ptr, ptr %sc_l_sawLauncher_0
  call void @scr_box_set_bool(ptr %t42, i1 true)
  %t43 = load ptr, ptr %sc_l_greet_0
  %t44 = call ptr @scr_box_get_ref(ptr %t43)
  %t45 = getelementptr inbounds %ScrClosure, ptr %t44, i64 0, i32 1
  %t46 = load ptr, ptr %t45
  call void %t46(ptr %t44)
  %t47 = call zeroext i1 @scr_exc_pending()
  br i1 %t47, label %exc.u7, label %exc.k8
exc.u7:
  call void @scr_closure_release(ptr %t44)
  %t48 = load ptr, ptr %sc_l_line_0
  call void @scr_str_release(ptr %t48)
  %t49 = load ptr, ptr %sc_l_chunk_0
  call void @scr_bytes_release(ptr %t49)
  ret void
exc.k8:
  call void @scr_closure_release(ptr %t44)
  br label %if.j6
if.j6:
  %t50 = load ptr, ptr %sc_l_buf_0
  %t51 = call ptr @scr_box_get_ref(ptr %t50)
  %t52 = call ptr @scr_str_retain_v(ptr @sc_lit_1)
  %t53 = call double @scr_str_index_of(ptr %t51, ptr %t52, double 0x0000000000000000)
  store double %t53, ptr %sc_l_i_0
  call void @scr_str_release(ptr %t51)
  call void @scr_str_release(ptr %t52)
  %t54 = load ptr, ptr %sc_l_line_0
  call void @scr_str_release(ptr %t54)
  br label %loop.c0
loop.e2:
  %t55 = load ptr, ptr %sc_l_chunk_0
  call void @scr_bytes_release(ptr %t55)
  ret void
}

define internal void @sc_f__x25_fn4(ptr %sc_env) #0 { ; %fn4
entry:
  %sc_l_greet_0 = alloca ptr ; greet
  %t0 = getelementptr inbounds %ScrClosure, ptr %sc_env, i64 1 ; caps
  %t1 = getelementptr inbounds ptr, ptr %t0, i64 0 ; caps[0]
  %t2 = load ptr, ptr %t1
  store ptr %t2, ptr %sc_l_greet_0 ; captured greet
  %t3 = load ptr, ptr %sc_l_greet_0
  %t4 = call ptr @scr_box_get_ref(ptr %t3)
  %t5 = getelementptr inbounds %ScrClosure, ptr %t4, i64 0, i32 1
  %t6 = load ptr, ptr %t5
  call void %t6(ptr %t4)
  %t7 = call zeroext i1 @scr_exc_pending()
  br i1 %t7, label %exc.u0, label %exc.k1
exc.u0:
  call void @scr_closure_release(ptr %t4)
  ret void
exc.k1:
  call void @scr_closure_release(ptr %t4)
  ret void
}

define internal void @sc_f__x25_fn6(ptr %sc_env) #0 { ; %fn6
entry:
  call void @scr_process_exit(double 0x0000000000000000)
  ret void
}

define internal void @sc_f__x25_fn5(ptr %sc_env) #0 { ; %fn5
entry:
  %sc_l_send_0 = alloca ptr ; send
  %t0 = getelementptr inbounds %ScrClosure, ptr %sc_env, i64 1 ; caps
  %t1 = getelementptr inbounds ptr, ptr %t0, i64 0 ; caps[0]
  %t2 = load ptr, ptr %t1
  store ptr %t2, ptr %sc_l_send_0 ; captured send
  %t3 = load ptr, ptr %sc_l_send_0
  %t4 = call ptr @scr_box_get_ref(ptr %t3)
  %t5 = call ptr @scr_str_retain_v(ptr @sc_lit_23)
  %t6 = getelementptr inbounds %ScrClosure, ptr %t4, i64 0, i32 1
  %t7 = load ptr, ptr %t6
  call void %t7(ptr %t4, ptr %t5)
  %t8 = call zeroext i1 @scr_exc_pending()
  br i1 %t8, label %exc.u0, label %exc.k1
exc.u0:
  call void @scr_closure_release(ptr %t4)
  ret void
exc.k1:
  call void @scr_closure_release(ptr %t4)
  %t9 = call ptr @scr_closure_new(ptr @sc_f__x25_fn6, i64 0)
  call void @scr_set_timeout(ptr %t9, double 0x4097700000000000)
  ret void
}

define internal void @sc_f__x25_fn0(ptr %sc_env, ptr %p_sc_l_conn_0) #0 { ; %fn0
entry:
  %sc_l_conn_0 = alloca ptr ; conn
  %sc_l_buf_0 = alloca ptr ; buf
  %sc_l_sawLauncher_0 = alloca ptr ; sawLauncher
  %sc_l_greeted_0 = alloca ptr ; greeted
  %sc_l_send_0 = alloca ptr ; send
  %sc_l_greet_0 = alloca ptr ; greet
  store ptr null, ptr %sc_l_buf_0
  store ptr null, ptr %sc_l_sawLauncher_0
  store ptr null, ptr %sc_l_greeted_0
  store ptr null, ptr %sc_l_send_0
  store ptr null, ptr %sc_l_greet_0
  %t0 = call ptr @scr_box_new_obj(ptr @scr_net_sock_retain_v, ptr @scr_net_sock_release_v, ptr null) ; conn (boxed param)
  call void @scr_box_set_ref(ptr %t0, ptr %p_sc_l_conn_0)
  store ptr %t0, ptr %sc_l_conn_0
  %t1 = call ptr @scr_str_retain_v(ptr @sc_lit_24)
  %t2 = call ptr @scr_str_retain_v(ptr @sc_lit_25)
  call void @sc_f_record(ptr %t1, ptr %t2)
  %t3 = call zeroext i1 @scr_exc_pending()
  br i1 %t3, label %exc.u0, label %exc.k1
exc.u0:
  %t4 = load ptr, ptr %sc_l_conn_0
  call void @scr_box_release(ptr %t4)
  ret void
exc.k1:
  %t5 = call ptr @scr_box_new(i32 2) ; let buf (boxed)
  store ptr %t5, ptr %sc_l_buf_0
  %t6 = call ptr @scr_str_retain_v(ptr @sc_lit_2)
  call void @scr_box_set_ref(ptr %t5, ptr %t6)
  %t7 = call ptr @scr_box_new(i32 1) ; let sawLauncher (boxed)
  store ptr %t7, ptr %sc_l_sawLauncher_0
  call void @scr_box_set_bool(ptr %t7, i1 false)
  %t8 = call ptr @scr_box_new(i32 1) ; let greeted (boxed)
  store ptr %t8, ptr %sc_l_greeted_0
  call void @scr_box_set_bool(ptr %t8, i1 false)
  %t9 = call ptr @scr_box_new(i32 4) ; let send (boxed)
  store ptr %t9, ptr %sc_l_send_0
  %t10 = call ptr @scr_closure_new(ptr @sc_f__x25_fn1_send, i64 1)
  %t11 = load ptr, ptr %sc_l_conn_0
  %t12 = call ptr @sc_retain_box(ptr %t11)
  %t13 = getelementptr inbounds %ScrClosure, ptr %t10, i64 1 ; caps
  %t14 = getelementptr inbounds ptr, ptr %t13, i64 0 ; caps[0]
  store ptr %t12, ptr %t14
  call void @scr_box_set_ref(ptr %t9, ptr %t10)
  %t15 = call ptr @scr_box_new(i32 4) ; let greet (boxed)
  store ptr %t15, ptr %sc_l_greet_0
  %t16 = call ptr @scr_closure_new(ptr @sc_f__x25_fn2_greet, i64 2)
  %t17 = load ptr, ptr %sc_l_greeted_0
  %t18 = call ptr @sc_retain_box(ptr %t17)
  %t19 = getelementptr inbounds %ScrClosure, ptr %t16, i64 1 ; caps
  %t20 = getelementptr inbounds ptr, ptr %t19, i64 0 ; caps[0]
  store ptr %t18, ptr %t20
  %t21 = load ptr, ptr %sc_l_send_0
  %t22 = call ptr @sc_retain_box(ptr %t21)
  %t23 = getelementptr inbounds %ScrClosure, ptr %t16, i64 1 ; caps
  %t24 = getelementptr inbounds ptr, ptr %t23, i64 1 ; caps[1]
  store ptr %t22, ptr %t24
  call void @scr_box_set_ref(ptr %t15, ptr %t16)
  %t25 = load ptr, ptr %sc_l_conn_0
  %t26 = call ptr @scr_box_get_ref(ptr %t25)
  %t27 = call ptr @scr_closure_new(ptr @sc_f__x25_fn3, i64 3)
  %t28 = load ptr, ptr %sc_l_buf_0
  %t29 = call ptr @sc_retain_box(ptr %t28)
  %t30 = getelementptr inbounds %ScrClosure, ptr %t27, i64 1 ; caps
  %t31 = getelementptr inbounds ptr, ptr %t30, i64 0 ; caps[0]
  store ptr %t29, ptr %t31
  %t32 = load ptr, ptr %sc_l_sawLauncher_0
  %t33 = call ptr @sc_retain_box(ptr %t32)
  %t34 = getelementptr inbounds %ScrClosure, ptr %t27, i64 1 ; caps
  %t35 = getelementptr inbounds ptr, ptr %t34, i64 1 ; caps[1]
  store ptr %t33, ptr %t35
  %t36 = load ptr, ptr %sc_l_greet_0
  %t37 = call ptr @sc_retain_box(ptr %t36)
  %t38 = getelementptr inbounds %ScrClosure, ptr %t27, i64 1 ; caps
  %t39 = getelementptr inbounds ptr, ptr %t38, i64 2 ; caps[2]
  store ptr %t37, ptr %t39
  call void @scr_net_sock_on_data(ptr %t26, ptr %t27, ptr @scr_net_data_thunk_bytes, i1 false)
  call void @scr_net_sock_release_v(ptr %t26)
  %t40 = call ptr @scr_closure_new(ptr @sc_f__x25_fn4, i64 1)
  %t41 = load ptr, ptr %sc_l_greet_0
  %t42 = call ptr @sc_retain_box(ptr %t41)
  %t43 = getelementptr inbounds %ScrClosure, ptr %t40, i64 1 ; caps
  %t44 = getelementptr inbounds ptr, ptr %t43, i64 0 ; caps[0]
  store ptr %t42, ptr %t44
  call void @scr_set_timeout(ptr %t40, double 0x40A3880000000000)
  %t45 = load i1, ptr @sc_g_e_stay
  %t46 = xor i1 %t45, true
  br i1 %t46, label %if.t2, label %if.j3
if.t2:
  %t47 = call ptr @scr_closure_new(ptr @sc_f__x25_fn5, i64 1)
  %t48 = load ptr, ptr %sc_l_send_0
  %t49 = call ptr @sc_retain_box(ptr %t48)
  %t50 = getelementptr inbounds %ScrClosure, ptr %t47, i64 1 ; caps
  %t51 = getelementptr inbounds ptr, ptr %t50, i64 0 ; caps[0]
  store ptr %t49, ptr %t51
  call void @scr_set_timeout(ptr %t47, double 0x40C1940000000000)
  br label %if.j3
if.j3:
  %t52 = load ptr, ptr %sc_l_conn_0
  call void @scr_box_release(ptr %t52)
  %t53 = load ptr, ptr %sc_l_buf_0
  call void @scr_box_release(ptr %t53)
  %t54 = load ptr, ptr %sc_l_sawLauncher_0
  call void @scr_box_release(ptr %t54)
  %t55 = load ptr, ptr %sc_l_greeted_0
  call void @scr_box_release(ptr %t55)
  %t56 = load ptr, ptr %sc_l_send_0
  call void @scr_box_release(ptr %t56)
  %t57 = load ptr, ptr %sc_l_greet_0
  call void @scr_box_release(ptr %t57)
  ret void
}

define internal void @sc_f__x25_fn9(ptr %sc_env, ptr %p_sc_l_code_0, ptr %p_sc_l__signal_0) #0 { ; %fn9
entry:
  %sc_l_code_0 = alloca ptr ; code
  %sc_l__signal_0 = alloca ptr ; _signal
  %sc_l_relay_0 = alloca ptr ; relay
  %s7 = alloca ptr
  %t0 = getelementptr inbounds %ScrClosure, ptr %sc_env, i64 1 ; caps
  %t1 = getelementptr inbounds ptr, ptr %t0, i64 0 ; caps[0]
  %t2 = load ptr, ptr %t1
  store ptr %t2, ptr %sc_l_relay_0 ; captured relay
  store ptr %p_sc_l_code_0, ptr %sc_l_code_0
  store ptr %p_sc_l__signal_0, ptr %sc_l__signal_0
  %t3 = call ptr @scr_str_retain_v(ptr @sc_lit_24)
  %t4 = call ptr @scr_str_retain_v(ptr @sc_lit_26)
  %t5 = load ptr, ptr %sc_l_code_0
  %t6 = call ptr @scr_union_retain_v(ptr %t5)
  %t8 = getelementptr inbounds %ScrUnion, ptr %t6, i64 0, i32 1
  %t9 = load i32, ptr %t8
  switch i32 %t9, label %u.bad1 [ i32 0, label %u.a2 i32 1, label %u.a3 ]
u.a2:
  %t10 = call double @scr_union_get_f64(ptr %t6)
  %t11 = call ptr @scr_f64_to_scrstr(double %t10)
  store ptr %t11, ptr %s7
  br label %us.j0
u.a3:
  %t12 = call ptr @scr_str_retain_v(ptr @sc_lit_27)
  store ptr %t12, ptr %s7
  br label %us.j0
u.bad1:
  call void @sc_bad_tag()
  unreachable
us.j0:
  %t13 = load ptr, ptr %s7
  %t14 = call ptr @scr_str_concat(ptr %t4, ptr %t13)
  call void @sc_f_record(ptr %t3, ptr %t14)
  %t15 = call zeroext i1 @scr_exc_pending()
  br i1 %t15, label %exc.u4, label %exc.k5
exc.u4:
  call void @scr_str_release(ptr %t4)
  call void @scr_union_release(ptr %t6)
  call void @scr_str_release(ptr %t13)
  %t16 = load ptr, ptr %sc_l_code_0
  call void @scr_union_release(ptr %t16)
  %t17 = load ptr, ptr %sc_l__signal_0
  call void @scr_union_release(ptr %t17)
  ret void
exc.k5:
  call void @scr_str_release(ptr %t4)
  call void @scr_union_release(ptr %t6)
  call void @scr_str_release(ptr %t13)
  %t18 = load ptr, ptr %sc_l_relay_0
  %t19 = call ptr @scr_box_get_ref(ptr %t18)
  %t20 = call ptr @scr_str_retain_v(ptr @sc_lit_28)
  %t21 = call i1 @scr_child_kill(ptr %t19, ptr %t20)
  %t22 = call zeroext i1 @scr_exc_pending()
  br i1 %t22, label %exc.u6, label %exc.k7
exc.u6:
  call void @scr_child_release_v(ptr %t19)
  call void @scr_str_release(ptr %t20)
  %t23 = load ptr, ptr %sc_l_code_0
  call void @scr_union_release(ptr %t23)
  %t24 = load ptr, ptr %sc_l__signal_0
  call void @scr_union_release(ptr %t24)
  ret void
exc.k7:
  call void @scr_child_release_v(ptr %t19)
  call void @scr_str_release(ptr %t20)
  call void @scr_process_exit(double 0x0000000000000000)
  %t25 = load ptr, ptr %sc_l_code_0
  call void @scr_union_release(ptr %t25)
  %t26 = load ptr, ptr %sc_l__signal_0
  call void @scr_union_release(ptr %t26)
  ret void
}

define internal void @sc_f__x25_fn8(ptr %sc_env) #0 { ; %fn8
entry:
  %sc_l_child_0 = alloca ptr ; child
  %sc_l_relay_0 = alloca ptr ; relay
  %s25 = alloca ptr
  %s30 = alloca double
  store ptr null, ptr %sc_l_child_0
  %t0 = getelementptr inbounds %ScrClosure, ptr %sc_env, i64 1 ; caps
  %t1 = getelementptr inbounds ptr, ptr %t0, i64 0 ; caps[0]
  %t2 = load ptr, ptr %t1
  store ptr %t2, ptr %sc_l_relay_0 ; captured relay
  %t3 = load ptr, ptr @sc_g_e_launcher
  %t4 = call ptr @scr_str_retain_v(ptr %t3)
  %t5 = call ptr @scr_arr_new(i32 2, i64 5)
  %t6 = load ptr, ptr @sc_g_e_page
  %t7 = call ptr @scr_str_retain_v(ptr %t6)
  %t8 = call double @scr_arr_push_ref(ptr %t5, ptr %t7)
  %t9 = load ptr, ptr @sc_g_e_SOCK
  %t10 = call ptr @scr_str_retain_v(ptr %t9)
  %t11 = call double @scr_arr_push_ref(ptr %t5, ptr %t10)
  %t12 = call ptr @scr_str_retain_v(ptr @sc_lit_29)
  %t13 = call double @scr_arr_push_ref(ptr %t5, ptr %t12)
  %t14 = call ptr @scr_str_retain_v(ptr @sc_lit_30)
  %t15 = call double @scr_arr_push_ref(ptr %t5, ptr %t14)
  %t16 = call ptr @scr_str_retain_v(ptr @sc_lit_31)
  %t17 = call double @scr_arr_push_ref(ptr %t5, ptr %t16)
  %t18 = call ptr @scr_arr_new(i32 2, i64 0)
  %t19 = call ptr @scr_str_retain_v(ptr @sc_lit_2)
  %t20 = call ptr @scr_spawn_opts(ptr %t4, ptr %t5, double 0x0000000000000000, double 0x3FF0000000000000, double 0x3FF0000000000000, double 0x0000000000000000, double 0x0000000000000000, i1 false, i1 false, ptr %t18, ptr %t19)
  store ptr %t20, ptr %sc_l_child_0
  call void @scr_str_release(ptr %t4)
  call void @scr_arr_release(ptr %t5)
  call void @scr_arr_release(ptr %t18)
  call void @scr_str_release(ptr %t19)
  %t21 = call ptr @scr_str_retain_v(ptr @sc_lit_24)
  %t22 = call ptr @scr_str_retain_v(ptr @sc_lit_32)
  %t23 = load ptr, ptr %sc_l_child_0
  %t24 = call ptr @scr_child_retain_v(ptr %t23)
  %t26 = call zeroext i1 @scr_child_has_pid(ptr %t24)
  br i1 %t26, label %hg.p0, label %hg.a1
hg.p0:
  %t27 = call double @scr_child_pid(ptr %t24)
  %t28 = call ptr @scr_union_new_f64(i32 0, double %t27)
  store ptr %t28, ptr %s25
  br label %hg.j2
hg.a1:
  store ptr @sc_unit_1, ptr %s25
  br label %hg.j2
hg.j2:
  %t29 = load ptr, ptr %s25
  %t31 = getelementptr inbounds %ScrUnion, ptr %t29, i64 0, i32 1
  %t32 = load i32, ptr %t31
  %t33 = icmp eq i32 %t32, 1
  br i1 %t33, label %nul.u3, label %nul.v4
nul.u3:
  call void @scr_union_release(ptr %t29)
  store double 0xBFF0000000000000, ptr %s30
  br label %nul.j5
nul.v4:
  %t34 = call double @scr_union_get_f64(ptr %t29)
  store double %t34, ptr %s30
  call void @scr_union_release(ptr %t29)
  br label %nul.j5
nul.j5:
  %t35 = load double, ptr %s30
  %t36 = call ptr @scr_f64_to_scrstr(double %t35)
  %t37 = call ptr @scr_str_concat(ptr %t22, ptr %t36)
  call void @sc_f_record(ptr %t21, ptr %t37)
  %t38 = call zeroext i1 @scr_exc_pending()
  br i1 %t38, label %exc.u6, label %exc.k7
exc.u6:
  call void @scr_str_release(ptr %t22)
  call void @scr_child_release_v(ptr %t24)
  call void @scr_str_release(ptr %t36)
  %t39 = load ptr, ptr %sc_l_child_0
  call void @scr_child_release_v(ptr %t39)
  ret void
exc.k7:
  call void @scr_str_release(ptr %t22)
  call void @scr_child_release_v(ptr %t24)
  call void @scr_str_release(ptr %t36)
  %t40 = load ptr, ptr %sc_l_child_0
  %t41 = call ptr @scr_child_retain_v(ptr %t40)
  %t42 = call ptr @scr_closure_new(ptr @sc_f__x25_fn9, i64 1)
  %t43 = load ptr, ptr %sc_l_relay_0
  %t44 = call ptr @sc_retain_box(ptr %t43)
  %t45 = getelementptr inbounds %ScrClosure, ptr %t42, i64 1 ; caps
  %t46 = getelementptr inbounds ptr, ptr %t45, i64 0 ; caps[0]
  store ptr %t44, ptr %t46
  call void @scr_child_on_exit(ptr %t41, ptr %t42, ptr @sc_cx_0)
  call void @scr_child_release_v(ptr %t41)
  %t47 = load ptr, ptr %sc_l_child_0
  call void @scr_child_release_v(ptr %t47)
  ret void
}

define internal void @sc_f__x25_fn7(ptr %sc_env) #0 { ; %fn7
entry:
  %sc_l_relayCmd_0 = alloca ptr ; relayCmd
  %sc_l_relay_0 = alloca ptr ; relay
  %s55 = alloca ptr
  %s60 = alloca double
  store ptr null, ptr %sc_l_relayCmd_0
  store ptr null, ptr %sc_l_relay_0
  %t0 = call ptr @scr_str_retain_v(ptr @sc_lit_24)
  %t1 = call ptr @scr_str_retain_v(ptr @sc_lit_33)
  %t2 = load double, ptr @sc_g_e_PORT
  %t3 = call ptr @scr_f64_to_scrstr(double %t2)
  %t4 = call ptr @scr_str_concat(ptr %t1, ptr %t3)
  call void @sc_f_record(ptr %t0, ptr %t4)
  %t5 = call zeroext i1 @scr_exc_pending()
  br i1 %t5, label %exc.u0, label %exc.k1
exc.u0:
  call void @scr_str_release(ptr %t1)
  call void @scr_str_release(ptr %t3)
  ret void
exc.k1:
  call void @scr_str_release(ptr %t1)
  call void @scr_str_release(ptr %t3)
  %t6 = call ptr @scr_str_retain_v(ptr @sc_lit_34)
  %t7 = load ptr, ptr @sc_g_e_SOCK
  %t8 = call ptr @scr_str_retain_v(ptr %t7)
  %t9 = call ptr @scr_str_concat(ptr %t6, ptr %t8)
  %t10 = call ptr @scr_str_retain_v(ptr @sc_lit_0)
  %t11 = call ptr @scr_str_concat(ptr %t9, ptr %t10)
  %t12 = load ptr, ptr @sc_g_e_FIFO
  %t13 = call ptr @scr_str_retain_v(ptr %t12)
  %t14 = call ptr @scr_str_concat(ptr %t11, ptr %t13)
  %t15 = call ptr @scr_str_retain_v(ptr @sc_lit_35)
  %t16 = call ptr @scr_str_concat(ptr %t14, ptr %t15)
  %t17 = load ptr, ptr @sc_g_e_FIFO
  %t18 = call ptr @scr_str_retain_v(ptr %t17)
  %t19 = call ptr @scr_str_concat(ptr %t16, ptr %t18)
  %t20 = call ptr @scr_str_retain_v(ptr @sc_lit_36)
  %t21 = call ptr @scr_str_concat(ptr %t19, ptr %t20)
  %t22 = call ptr @scr_str_retain_v(ptr @sc_lit_37)
  %t23 = load ptr, ptr @sc_g_e_SOCK
  %t24 = call ptr @scr_str_retain_v(ptr %t23)
  %t25 = call ptr @scr_str_concat(ptr %t22, ptr %t24)
  %t26 = call ptr @scr_str_retain_v(ptr @sc_lit_38)
  %t27 = call ptr @scr_str_concat(ptr %t25, ptr %t26)
  %t28 = load ptr, ptr @sc_g_e_FIFO
  %t29 = call ptr @scr_str_retain_v(ptr %t28)
  %t30 = call ptr @scr_str_concat(ptr %t27, ptr %t29)
  %t31 = call ptr @scr_str_retain_v(ptr @sc_lit_39)
  %t32 = call ptr @scr_str_concat(ptr %t30, ptr %t31)
  %t33 = load double, ptr @sc_g_e_PORT
  %t34 = call ptr @scr_f64_to_scrstr(double %t33)
  %t35 = call ptr @scr_str_concat(ptr %t32, ptr %t34)
  %t36 = call ptr @scr_str_retain_v(ptr @sc_lit_40)
  %t37 = call ptr @scr_str_concat(ptr %t35, ptr %t36)
  %t38 = load ptr, ptr @sc_g_e_FIFO
  %t39 = call ptr @scr_str_retain_v(ptr %t38)
  %t40 = call ptr @scr_str_concat(ptr %t37, ptr %t39)
  %t41 = call ptr @scr_str_concat(ptr %t21, ptr %t40)
  store ptr %t41, ptr %sc_l_relayCmd_0
  call void @scr_str_release(ptr %t6)
  call void @scr_str_release(ptr %t8)
  call void @scr_str_release(ptr %t9)
  call void @scr_str_release(ptr %t10)
  call void @scr_str_release(ptr %t11)
  call void @scr_str_release(ptr %t13)
  call void @scr_str_release(ptr %t14)
  call void @scr_str_release(ptr %t15)
  call void @scr_str_release(ptr %t16)
  call void @scr_str_release(ptr %t18)
  call void @scr_str_release(ptr %t19)
  call void @scr_str_release(ptr %t20)
  call void @scr_str_release(ptr %t21)
  call void @scr_str_release(ptr %t22)
  call void @scr_str_release(ptr %t24)
  call void @scr_str_release(ptr %t25)
  call void @scr_str_release(ptr %t26)
  call void @scr_str_release(ptr %t27)
  call void @scr_str_release(ptr %t29)
  call void @scr_str_release(ptr %t30)
  call void @scr_str_release(ptr %t31)
  call void @scr_str_release(ptr %t32)
  call void @scr_str_release(ptr %t34)
  call void @scr_str_release(ptr %t35)
  call void @scr_str_release(ptr %t36)
  call void @scr_str_release(ptr %t37)
  call void @scr_str_release(ptr %t39)
  call void @scr_str_release(ptr %t40)
  %t42 = call ptr @scr_box_new_obj(ptr @scr_child_retain_v, ptr @scr_child_release_v, ptr null) ; let relay (boxed)
  store ptr %t42, ptr %sc_l_relay_0
  %t43 = call ptr @scr_str_retain_v(ptr @sc_lit_41)
  %t44 = call ptr @scr_arr_new(i32 2, i64 2)
  %t45 = call ptr @scr_str_retain_v(ptr @sc_lit_42)
  %t46 = call double @scr_arr_push_ref(ptr %t44, ptr %t45)
  %t47 = load ptr, ptr %sc_l_relayCmd_0
  %t48 = call ptr @scr_str_retain_v(ptr %t47)
  %t49 = call double @scr_arr_push_ref(ptr %t44, ptr %t48)
  %t50 = call ptr @scr_spawn(ptr %t43, ptr %t44)
  call void @scr_box_set_ref(ptr %t42, ptr %t50)
  call void @scr_str_release(ptr %t43)
  call void @scr_arr_release(ptr %t44)
  %t51 = call ptr @scr_str_retain_v(ptr @sc_lit_24)
  %t52 = call ptr @scr_str_retain_v(ptr @sc_lit_43)
  %t53 = load ptr, ptr %sc_l_relay_0
  %t54 = call ptr @scr_box_get_ref(ptr %t53)
  %t56 = call zeroext i1 @scr_child_has_pid(ptr %t54)
  br i1 %t56, label %hg.p2, label %hg.a3
hg.p2:
  %t57 = call double @scr_child_pid(ptr %t54)
  %t58 = call ptr @scr_union_new_f64(i32 0, double %t57)
  store ptr %t58, ptr %s55
  br label %hg.j4
hg.a3:
  store ptr @sc_unit_1, ptr %s55
  br label %hg.j4
hg.j4:
  %t59 = load ptr, ptr %s55
  %t61 = getelementptr inbounds %ScrUnion, ptr %t59, i64 0, i32 1
  %t62 = load i32, ptr %t61
  %t63 = icmp eq i32 %t62, 1
  br i1 %t63, label %nul.u5, label %nul.v6
nul.u5:
  call void @scr_union_release(ptr %t59)
  store double 0xBFF0000000000000, ptr %s60
  br label %nul.j7
nul.v6:
  %t64 = call double @scr_union_get_f64(ptr %t59)
  store double %t64, ptr %s60
  call void @scr_union_release(ptr %t59)
  br label %nul.j7
nul.j7:
  %t65 = load double, ptr %s60
  %t66 = call ptr @scr_f64_to_scrstr(double %t65)
  %t67 = call ptr @scr_str_concat(ptr %t52, ptr %t66)
  call void @sc_f_record(ptr %t51, ptr %t67)
  %t68 = call zeroext i1 @scr_exc_pending()
  br i1 %t68, label %exc.u8, label %exc.k9
exc.u8:
  call void @scr_str_release(ptr %t52)
  call void @scr_child_release_v(ptr %t54)
  call void @scr_str_release(ptr %t66)
  %t69 = load ptr, ptr %sc_l_relayCmd_0
  call void @scr_str_release(ptr %t69)
  %t70 = load ptr, ptr %sc_l_relay_0
  call void @scr_box_release(ptr %t70)
  ret void
exc.k9:
  call void @scr_str_release(ptr %t52)
  call void @scr_child_release_v(ptr %t54)
  call void @scr_str_release(ptr %t66)
  %t71 = call ptr @scr_closure_new(ptr @sc_f__x25_fn8, i64 1)
  %t72 = load ptr, ptr %sc_l_relay_0
  %t73 = call ptr @sc_retain_box(ptr %t72)
  %t74 = getelementptr inbounds %ScrClosure, ptr %t71, i64 1 ; caps
  %t75 = getelementptr inbounds ptr, ptr %t74, i64 0 ; caps[0]
  store ptr %t73, ptr %t75
  call void @scr_set_timeout(ptr %t71, double 0x407F400000000000)
  %t76 = load ptr, ptr %sc_l_relayCmd_0
  call void @scr_str_release(ptr %t76)
  %t77 = load ptr, ptr %sc_l_relay_0
  call void @scr_box_release(ptr %t77)
  ret void
}

declare void @scr_exc_print_uncaught()

define i32 @main(i32 %argc, ptr %argv) #0 {
entry:
  call void @scr_init()
  store i64 0, ptr getelementptr inbounds ([5 x %ScrVt], ptr @scr_error_vts, i64 0, i64 0, i32 0)
  store i64 4, ptr getelementptr inbounds ([5 x %ScrVt], ptr @scr_error_vts, i64 0, i64 0, i32 1) ; Error
  store i64 1, ptr getelementptr inbounds ([5 x %ScrVt], ptr @scr_error_vts, i64 0, i64 1, i32 0)
  store i64 1, ptr getelementptr inbounds ([5 x %ScrVt], ptr @scr_error_vts, i64 0, i64 1, i32 1) ; TypeError
  store i64 2, ptr getelementptr inbounds ([5 x %ScrVt], ptr @scr_error_vts, i64 0, i64 2, i32 0)
  store i64 2, ptr getelementptr inbounds ([5 x %ScrVt], ptr @scr_error_vts, i64 0, i64 2, i32 1) ; RangeError
  store i64 3, ptr getelementptr inbounds ([5 x %ScrVt], ptr @scr_error_vts, i64 0, i64 3, i32 0)
  store i64 3, ptr getelementptr inbounds ([5 x %ScrVt], ptr @scr_error_vts, i64 0, i64 3, i32 1) ; SyntaxError
  store i64 4, ptr getelementptr inbounds ([5 x %ScrVt], ptr @scr_error_vts, i64 0, i64 4, i32 0)
  store i64 4, ptr getelementptr inbounds ([5 x %ScrVt], ptr @scr_error_vts, i64 0, i64 4, i32 1) ; DOMException
  call void @scr_net_install()
  call void @scr_net_dyn_install()
  call void @scr_lib_init(i32 %argc, ptr %argv)
  call void @sc_f__x25_main()
  %exc = call zeroext i1 @scr_exc_pending()
  br i1 %exc, label %uncaught, label %ok
uncaught:
  call void @scr_exc_print_uncaught()
  %gu0 = load ptr, ptr @sc_g_e_launcher
  call void @scr_str_release(ptr %gu0) ; launcher
  %gu1 = load ptr, ptr @sc_g_e_page
  call void @scr_str_release(ptr %gu1) ; page
  %gu4 = load ptr, ptr @sc_g_e_SOCK
  call void @scr_str_release(ptr %gu4) ; SOCK
  %gu5 = load ptr, ptr @sc_g_e_FIFO
  call void @scr_str_release(ptr %gu5) ; FIFO
  %gu6 = load ptr, ptr @sc_g_e_LOG
  call void @scr_str_release(ptr %gu6) ; LOG
  %gu7 = load ptr, ptr @sc_g_e_server
  call void @scr_net_server_release_v(ptr %gu7) ; server
  ret i32 1
ok:
  %loop_rejection = call zeroext i1 @scr_loop_run(ptr null)
  %lexc = call zeroext i1 @scr_exc_pending()
  br i1 %lexc, label %luncaught, label %lok
luncaught:
  call void @scr_exc_print_uncaught()
  %gl0 = load ptr, ptr @sc_g_e_launcher
  call void @scr_str_release(ptr %gl0) ; launcher
  %gl1 = load ptr, ptr @sc_g_e_page
  call void @scr_str_release(ptr %gl1) ; page
  %gl4 = load ptr, ptr @sc_g_e_SOCK
  call void @scr_str_release(ptr %gl4) ; SOCK
  %gl5 = load ptr, ptr @sc_g_e_FIFO
  call void @scr_str_release(ptr %gl5) ; FIFO
  %gl6 = load ptr, ptr @sc_g_e_LOG
  call void @scr_str_release(ptr %gl6) ; LOG
  %gl7 = load ptr, ptr @sc_g_e_server
  call void @scr_net_server_release_v(ptr %gl7) ; server
  ret i32 1
lok:
  br i1 %loop_rejection, label %lreported, label %lclean
lreported:
  call void @scr_discard_unhandled_rejections()
  %gq0 = load ptr, ptr @sc_g_e_launcher
  call void @scr_str_release(ptr %gq0) ; launcher
  %gq1 = load ptr, ptr @sc_g_e_page
  call void @scr_str_release(ptr %gq1) ; page
  %gq4 = load ptr, ptr @sc_g_e_SOCK
  call void @scr_str_release(ptr %gq4) ; SOCK
  %gq5 = load ptr, ptr @sc_g_e_FIFO
  call void @scr_str_release(ptr %gq5) ; FIFO
  %gq6 = load ptr, ptr @sc_g_e_LOG
  call void @scr_str_release(ptr %gq6) ; LOG
  %gq7 = load ptr, ptr @sc_g_e_server
  call void @scr_net_server_release_v(ptr %gq7) ; server
  ret i32 1
lclean:
  %rej = call zeroext i1 @scr_report_unhandled_rejections()
  br i1 %rej, label %lrej, label %lrok
lrej:
  %gr0 = load ptr, ptr @sc_g_e_launcher
  call void @scr_str_release(ptr %gr0) ; launcher
  %gr1 = load ptr, ptr @sc_g_e_page
  call void @scr_str_release(ptr %gr1) ; page
  %gr4 = load ptr, ptr @sc_g_e_SOCK
  call void @scr_str_release(ptr %gr4) ; SOCK
  %gr5 = load ptr, ptr @sc_g_e_FIFO
  call void @scr_str_release(ptr %gr5) ; FIFO
  %gr6 = load ptr, ptr @sc_g_e_LOG
  call void @scr_str_release(ptr %gr6) ; LOG
  %gr7 = load ptr, ptr @sc_g_e_server
  call void @scr_net_server_release_v(ptr %gr7) ; server
  ret i32 1
lrok:
  %g0 = load ptr, ptr @sc_g_e_launcher
  call void @scr_str_release(ptr %g0) ; launcher
  %g1 = load ptr, ptr @sc_g_e_page
  call void @scr_str_release(ptr %g1) ; page
  %g4 = load ptr, ptr @sc_g_e_SOCK
  call void @scr_str_release(ptr %g4) ; SOCK
  %g5 = load ptr, ptr @sc_g_e_FIFO
  call void @scr_str_release(ptr %g5) ; FIFO
  %g6 = load ptr, ptr @sc_g_e_LOG
  call void @scr_str_release(ptr %g6) ; LOG
  %g7 = load ptr, ptr @sc_g_e_server
  call void @scr_net_server_release_v(ptr %g7) ; server
  ret i32 0
}

attributes #0 = { sanitize_address }
